---

- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: raspberrypi-config
    - role: k3s-download

- hosts: master
  become: yes
  roles:
    - role: k3s-master
    - role: kube-config-save

- hosts: node
  become: yes
  roles:
    - role: k3s-node

- hosts: tools
  become: yes
  roles:
    - role: helm-install
    - role: kube-config-copy
    - role: helm-dashboard
    - role: helm-longhorn
    - role: helm-ingress-nginx
